.editorconfig, README.md, src/App.css, src/components/Navbar.css, src/components/Navbar.js, src/serviceWorker.js
I cleaned non uniform indentations from files. I added .editorconfig file and necessary settings to avoid style problems in future. Let's hope this helps.
=> Cleaning files after navbar pull request.

.vscode/settings.json, CSSHTML/index.html, CSSHTML/style.css, package-lock.json, questionnaire/questionnaire.css, questionnaire/questionnaire.html
Hi, questionnaire folder with html css files added. Please check !
=> questionnaire folder with html css files added

questionnaire/index.js, questionnaire/questionnaire.css, questionnaire/questionnaire.html
Added static parts of mobile version, please check.
=> Survey desktop version

questionnaire/questionnaire.css, questionnaire/questionnaire.html
=> Altynay branch

questionnaire/questionnaire.css, questionnaire/questionnaire.html
changed color variables and added responsiveness to desktop
=> changed color variables and added responsiveness to desktop

questionnaire/index.js, questionnaire/questionnaire.css, questionnaire/questionnaire.html
=> added progress bar and cicle

questionnaire/questionnaire.css, questionnaire/questionnaire.html
=> mobile responsiveness added

questionnaire/questionnaire.css, questionnaire/questionnaire.html
=> desktop responsive working

questionnaire/index.js
=> js part added

questionnaire/questionnaire.css
set display for responsive-section
=> set display for responsive-section

questionnaire/index.js, questionnaire/questionnaire.css, questionnaire/questionnaire.html
added color changing functionality for mobile version
=> added color changing functionality for mobile version

questionnaire/questionnaire.css, questionnaire/questionnaire.html
=> mobile styled

questionnaire/questionnaire.css
=> changed styling

questionnaire/questionnaire.css, questionnaire/questionnaire.html
did some adjustments to survey styling
=> did some adjustments to survey styling

src/app/store.js, src/components/Header.jsx, src/components/pages/MySurveys.js, src/index.js, src/store/index.js, src/store/surveys/actions.js, src/store/surveys/reducer.js, src/store/user/actions.js, src/store/user/reducer.js
I added user and survey reducers. Surveys are fetch from Happy-server using redux thunk.
=> Redux basic functionality

src/components/Header.jsx, src/components/Notification/NotificationBell.js
added notification bell to the header
=> added notification bell to the header

src/components/Header.jsx, src/components/LeftBar/Leftbar.style.js, src/components/pages/Data.js
=> removed header transparent

src/App.js, src/components/LeftBar/Leftbar.jsx, src/components/pages/Home.js, src/components/pages/MySurveys.js, src/components/pages/homePage/HomeCard.js, src/components/pages/homePage/HomePageData.js
=> Routing refactor

src/components/pages/Home.js, src/components/pages/homePage/HomeCard.js, src/components/pages/homePage/HomePageData.js
added links to the home card buttons
=> added links to the home card buttons

src/components/LeftBar/Leftbar.jsx
=> added link to the logo

src/components/Header.jsx, src/components/LeftBar/Leftbar.jsx, src/components/pages/MySurveys.js
Changed search bar position and added functionality to it.
=> Leftbar logo

src/App.js, src/components/LeftBar/Leftbar.jsx, src/components/pages/Embed.js
=> added embed page

src/components/pages/MySurveys.js
solved search background color problem
=> solved search background color problem

src/components/Header.jsx, src/components/pages/Data.js
changed border radius of date(follows design)
=> changed border radius of date

src/components/pages/homePage/HomeCard.js
=> changed styling for home page

src/components/pages/CreateNewSurvey.js
changed textTransform for save button
=> changed textTransform for save button
